name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

    #  - name: Run tests
    #    run: pytest tests/

      - name: Build Docker image
        run: docker build -t data-pipeline .



    # This deploy part currently does not deploy anything on AWS or Render
    # We have got to configure this, the tentative deployment script

      #- name: Deploy to Server
      #  run: |
      #    ssh user@yserver-ip 'docker pull my_docker_user/data-pipeline:latest && docker run -d -p 8000:8000 my_docker_user/data-pipeline'
      # Upon decided, it may require to set up SSH keys for GitHub Actions to connect.

      - name: Deploy
        run: echo "Deploying application..."  
